server:
  port: 8080

spring:
  datasource:
    username: root
    password: deadloonymy!!1
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

indexing-settings:
  sitesConfig:
    - url: https://www.playback.ru/
      name: PlayBack.Ru
      timeout: 300
    - url: https://www.svetlovka.ru/
      name: Svetlovka
    - url: https://et-cetera.ru/
      name: Et-cetera
      timeout: 400


